version: '3'
services:
  server:
    image: node:14
    working_dir: /server
    volumes:
      - type: bind
        source: ./server
        target: /server
  db:
    image: 'postgres:latest'
    environment:
     - POSTGRES_USER=postgres
    volumes:
      - "./server/db:/docker-entrypoint-initdb.d/:ro"


